# Generated by Django 2.2 on 2022-02-10 11:48

import cosinnus_event.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosinnus_event', '0021_auto_20211022_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferenceevent',
            name='is_confidential',
        ),
        migrations.AddField(
            model_name='conferenceevent',
            name='is_public',
            field=models.BooleanField(default=True, help_text="Provides an option to choose if the event's description should be shown publicly or not", verbose_name='Event is public'),
        ),
        migrations.AddField(
            model_name='conferenceevent',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Provides an option to choose if the particular event should be shown on microsite or not', verbose_name='Event is visible'),
        ),
    ]
